"""DXDCNet constants."""

DEVICE_TYPE_COMMAND_STATION = 0x0
DEVICE_TYPE_PC = 0x1
DEVICE_TYPE_THROTTLE = 0x1
DEVICE_TYPE_BOOSTER = 0x7
DEVICE_TYPE_SPECIAL = 0xF

CMD_MAC_REQUEST = 0x0B
CMD_MAC_ADDRESS = 0x0C
CMD_LOCO_CONTROL_REQUEST = 0x04
CMD_LOCO_CONTROL_ACK = 0x07
CMD_LOCO_CONTROL_RELEASE = 0x08
CMD_LOCO_SPEED = 0x10
CMD_LOCO_FUNCTION = 0x11
CMD_PROGRAM_TRACK_STANDARD = 0x14
CMD_PROGRAM_TRACK_ACK = 0x15
CMD_PROGRAM_TRACK_SLOW = 0x16
CMD_PROGRAM_TRACK_VALUE = 0x17
CMD_TRACK_OUTPUT = 0x20
CMD_REQUEST_DEVICE_STATUS = 0x22
CMD_DEVICE_STATUS = 0x23
CMD_REQUEST_LOCO_STATUS = 0x2A
CMD_LOCO_STATUS = 0x2B
CMD_PARAMETER_SET = 0x40
CMD_PARAMETER_READ = 0x41
CMD_PARAMETER_VALUE = 0x42
CMD_VERSION_REQUEST = 0x84
CMD_VERSION_DATA = 0x85
CMD_DCC_PACKET = 0x8A

D9000_CURRENT_LIMIT_STEP_MA = 40

TRACK_OUTPUT_POWER_ON = 0x80
TRACK_OUTPUT_DC_MODE = 0x40
TRACK_OUTPUT_DC_DIRECTION_POSITIVE = 0x20
TRACK_OUTPUT_AUTO_REPORT = 0x10

SPEED_MODE_14 = 0x00
SPEED_MODE_28 = 0x01
SPEED_MODE_128 = 0x02

WARNING_CHECKSUM_UNCONFIRMED = "udp_checksum_algorithm_unconfirmed"
WARNING_CHECKSUM_INVALID = "udp_checksum_invalid"
WARNING_LENGTH_MISMATCH = "udp_length_mismatch"

PROGRAMMER_OP_NORMAL = 0x0
PROGRAMMER_OP_ACCESSORY = 0x1
PROGRAMMER_OP_DECODER_MAC = 0x3
PROGRAMMER_OP_MAIN_LOCO_POM = 0x6
PROGRAMMER_OP_MAIN_ACCESSORY_POM = 0x7

PROGRAMMER_MODE_PAGE_CHECK = 0x0
PROGRAMMER_MODE_PAGE_WRITE = 0x1
PROGRAMMER_MODE_DIRECT_READ = 0x4
PROGRAMMER_MODE_DIRECT_CHECK = 0x5
PROGRAMMER_MODE_DIRECT_BIT = 0x6
PROGRAMMER_MODE_DIRECT_WRITE = 0x7

PROGRAMMER_BIT_CHECK = 0x0
PROGRAMMER_BIT_WRITE = 0x1

PROGRAMMER_ACK_BUSY = 0x0
PROGRAMMER_ACK_OVERLOAD = 0x1
PROGRAMMER_ACK_NOACK = 0x2
PROGRAMMER_ACK_ACK = 0x3
PROGRAMMER_ACK_NOPOWER = 0x4
PROGRAMMER_ACK_NOLOC = 0x7

PROGRAMMER_ACK_NAMES = {
  PROGRAMMER_ACK_BUSY: "busy",
  PROGRAMMER_ACK_OVERLOAD: "overload",
  PROGRAMMER_ACK_NOACK: "noack",
  PROGRAMMER_ACK_ACK: "ack",
  PROGRAMMER_ACK_NOPOWER: "nopower",
  PROGRAMMER_ACK_NOLOC: "noloc",
}
