"""Shared public URL path prefixes served by the local gateway."""

ASSET_PUBLIC_PREFIX = "/assets/"
MANUAL_ASSET_PUBLIC_PREFIX = "/manual/assets/"
CONTROLLER_CONFIG_RELATIVE_PREFIX = "config/controllers/"
CONTROLLER_CONFIG_PUBLIC_PREFIX = f"/{CONTROLLER_CONFIG_RELATIVE_PREFIX}"
VEHICLE_IMAGE_PUBLIC_PREFIX = "/data/vehicle-images/"
VEHICLE_TYPE_ICON_PUBLIC_PREFIX = "/assets/icons/vehicle-types/"

STATIC_PUBLIC_PREFIXES = (
  ASSET_PUBLIC_PREFIX,
  MANUAL_ASSET_PUBLIC_PREFIX,
  VEHICLE_IMAGE_PUBLIC_PREFIX,
)

ALLOWED_VEHICLE_IMAGE_PATH_PREFIXES = (
  VEHICLE_IMAGE_PUBLIC_PREFIX,
  VEHICLE_TYPE_ICON_PUBLIC_PREFIX,
)
